name: Build, Test and Secure SYNOPSIS

on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
    - cron: '0 3 * * 0' # run weekly on Sundays

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential lcov curl unzip python3-pip

      - name: Configure project
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build -- -j$(nproc)

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: synopsis-binaries
          path: |
            build/bin/
            build/lib/

      - name: Upload test logs (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: build/Testing/Temporary/LastTest.log

  codeql:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v3
        with:
          languages: cpp, python
      - uses: github/codeql-action/autobuild@v3
      - uses: github/codeql-action/analyze@v3
        with:
          category: "codeql"

  semgrep:
    name: Semgrep
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep (Community Rules)
        run: |
          semgrep --config=auto --json > semgrep-report.json 
          semgrep --config=auto --sarif > semgrep-report.sarif
        continue-on-error: true

      - name: Upload Semgrep JSON Report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-json-report
          path: semgrep-report.json

      - name: Upload Semgrep SARIF Report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-sarif-report
          path: semgrep-report.sarif

      - name: Upload Semgrep SARIF to GitHub Security Tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-report.sarif
        continue-on-error: true


  gitleaks:
    name: gitleaks
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }} # Only required for Organizations, not personal accounts.

  syft-grype:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Install Syft
        run: |
          SYFT_VERSION=v1.32.0
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin $SYFT_VERSION
      - name: Install Grype
        run: |
          GRYPE_VERSION=v0.99.1
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin $GRYPE_VERSION
      - name: Generate SPDX SBOM
        run: syft dir:. -o spdx-json > sbom.spdx.json
      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom-syft
          path: sbom.spdx.json
      - name: Scan SBOM with Grype
        run: grype sbom:sbom.spdx.json -o sarif > grype.sarif || true
      - name: Upload Grype SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: grype.sarif
      - name: Upload Grype Report
        uses: actions/upload-artifact@v4
        with:
          name: grype-report
          path: grype.sarif

  # osv-scanner:
  #   name: osv-scanner
  #   runs-on: ubuntu-latest
  #   needs: syft-grype
  #   permissions:
  #     contents: read
  #     security-events: write
  #   continue-on-error: true
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Download SPDX SBOM
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: sbom-syft
  #         path: .

  #     - name: Install OSV-Scanner
  #       run: |
  #         OSV_VERSION="v2.2.2"
  #         curl -sSL https://github.com/google/osv-scanner/releases/download/${OSV_VERSION}/osv-scanner_linux_amd64 -o /usr/local/bin/osv-scanner
  #         chmod +x /usr/local/bin/osv-scanner

  #     - name: Run OSV-Scanner on SBOM
  #       run: |
  #          # Always produce SARIF, even if some packages are unscannable
  #          osv-scanner --sbom sbom.spdx.json --format sarif > osv.sarif || echo '{"runs":[]}' > osv.sarif

  #     - name: Upload SARIF to Security tab
  #       if: always()
  #       uses: github/codeql-action/upload-sarif@v3
  #       with:
  #         sarif_file: osv.sarif

  #     - name: Upload OSV Report
  #       if: always()
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: osv-report
  #         path: osv.sarif

 
  security-summary:
    runs-on: ubuntu-latest
    needs: [codeql, semgrep, gitleaks, syft-grype]
    steps:
      - name: Download all reports
        uses: actions/download-artifact@v4
        with:
          path: reports
      - name: Organize reports
        run: |
          mkdir -p summary
          cp -r reports/* summary/ || true
          zip -r security-summary.zip summary
      - name: Upload Security Summary
        uses: actions/upload-artifact@v4
        with:
          name: security-summary
          path: security-summary.zip
